export const BASE_ENDPOINT = process.env.REACT_SPOTIFY_BASE_URL!;
export const REDIRECT_URI = process.env.REACT_APP_REDIRECT_URI!;

export const CLIENT_AUTH_TOKEN_ENDPOINT =
  process.env.REACT_APP_CLIENT_AUTH_TOKEN_ENDPOINT!;
export const NEW_RELEASES_ENDPOINT =
  process.env.REACT_APP_NEW_RELEASES_ENDPOINT!;
